### ISSUE TITLE
[Feature request] Allow check against permissions.

### ISSUE THREAD

**Issue by brazorf** [Narzerus/angular-permission#100]
Very interesting module.

I feel it lacks one major feature though, since you're not able to set permissions on user basis.

Example:
```javascript
data: {
  permissions: {
    // Ok, we allow admins the access.
    only: ['admins'], 

    // What we are not able to do actually is check 
    // whether a single user has a set of given permissions,
    // regardless of his roles.
    permissions: ['publish.content'] 
  }
},
```

I think this would be a great feature to add in.

**Comment by Narzerus** [comment]
Oh, yeah, so basically `Permission` is not that clear in the sense that it depends on the user if the library is used with roles or permissions.

You could actually make it work for your usage. You would have to define many roles as permissions though.


One major update would be to create permissions and assign them to roles, then you can grant/revoke access based on permissions or roles.

I plan to implement this at some point, but it will probably happen after a full rewrite of this library. Angular 2.0 maybe?

**Comment by brazorf** [comment]
Glad to hear this is a planned feature. Drop me a line if you'll need help developing the new version, i'd be glad to help if possible.

Meanwhile i think i'll stick with the workaround you suggested.
