### ISSUE TITLE
Check for multiple roles

### ISSUE THREAD

**Issue by vectorderivative** [Narzerus/angular-permission#104]
Maybe I'm missing something from the documentation.
How do I validate a user with multiple roles?
For example, I want an area restricted to just admins who also are other type of user.

**Comment by Narzerus** [comment]
You can use the `only` permission:

```javascript
permissions: {
  only: ['User', 'Admin']
}
```

Or depending on how your roles are defined, just `Admin` could be fine if that implies an `Admin` is always a `User`
