### ISSUE TITLE
Feature Request: Catch-All validation function.

### ISSUE THREAD

**Issue by TravisTX** [Narzerus/angular-permission#12]
This is a convenience feature request.

Problem: I have lots of roles, the user is either in them or not, there is no complex logic.  An angular service is holding an array of all the roles the current user is in.  Currently with angular-permissions, I have to define every role, and write essentially the same function for each one.  I imagine this is a pretty common scenario.

Proposed Solution: Allow the developer to specify a "catch-all" validation function that is used for any undefined roles at the time the user tries to navigate to the route.  It would need to differ slightly from the existing validation functions, in that it would need an input parameter stating the role name that is being checked for.  But I think this would be a good addition to the existing validation functions anyway.

**Comment by Narzerus** [comment]
After some thought I think this role based access are currently the way to go, It is how the module is currently being used. I think the idea of permissions is quite interesting but it doesn't fit the current implementation. So for now I will not move forward on this idea.

**Comment by LordWingZero** [comment]
Just want to throw my vote in here for this feature. Not sure why we have to sit there and define every single row one by one instead of being able to define them in an array.
