### ISSUE TITLE
'only' array not checking both permissions..

### ISSUE THREAD

**Issue by lansanaacam** [Narzerus/angular-permission#197]
I have some permissions define, for example they look like this:

```
        PermissionStore.definePermission('isAuthenticated', isAuthenticated);
        PermissionStore.definePermission('isEditableByUser', isEditableByUser);

        function isAuthenticated() {
            return $auth.isAuthenticated();
        }

        function isEditableByUser(stateParams) {
            var deferred = $q.defer();

            articleService
                .verifyEdit(stateParams.articleSlug)
                .then(function(res) {
                    if (res.status == 200) {
                        deferred.resolve();
                    } else {
                        deferred.reject();
                    }
                })
                .catch(function() {
                    deferred.reject();
                });

            return deferred.promise;
        }
```

...And in my state I have:

```
               data: {
                    permissions: {
                        only: ['isEditableByUser', 'isAuthenticated'],
                        redirectTo: 'app.home'
                    }
                },
```

The problem is that both permissions are not being checked.. the `isAuthenticated` permissions passes so the state is entered, however the `isEditableByUser` state fails yet no redirect happens. When I remove `isAuthenticated`, it works how it should, but when I have both, just one of them returning true lets the user pass.

Why is this happening? I thought it should check both permissions?

**Comment by tomfumb** [comment]
@lansanaacam can you please clarify why you closed this issue? I'm having the same problem

**Comment by LansanaCamara** [comment]
Hi @tomfumb 

This was a while ago, so I'm not exactly sure _what_ or _why_ my solution was, however looking at the code I can see that I turned the `isEditableByUser` from a permission into a role. For instance:

`

        /**
         * Define all permissions for app.
         */
        function initializePermissions() {
            PermissionStore.definePermission('isAnonymous', isAnonymous);
            PermissionStore.definePermission('isAuthenticated', isAuthenticated);
            PermissionStore.definePermission('isTokenValid', isTokenValid);
        }

        /**
         * Define all roles for the app.
         */
        function initializeRoles() {
            RoleStore.defineRole('isEditableByUser', [], isEditableByUser);
        }
`

**Comment by tomfumb** [comment]
Thanks, I arrived at the same solution. This seems like a bit of an awkward way to do things, I think the ideal approach would include a way to define and/or in the permissions-only array

**Comment by LansanaCamara** [comment]
I agree. It's much more intuitive to just add an array of permissions that
must all be passed, as opposed to one permission that has certain roles on
it.
