### ISSUE TITLE
Permission is not a constructor

### ISSUE THREAD

**Issue by stenmuchow** [Narzerus/angular-permission#245]
I dont really understand what I am doing wrong. 

angular-permission.js:436 Uncaught TypeError: Permission is not a constructor

I am simply using this: 

``` 
   var permissions = [
        'isLoggedIn',
        'seeAdminDashboard',
        'seeAdminUsers',
        'seeAdminStructure',
        'seeAdminContractCategories',
        'seeAdminCustomFields',
        'seeAdminSettings'
    ];

    PermissionStore.definePermission(permissions, function() {
        return true;
    });

```

**Comment by axar** [comment]
Maybe haven't injected ? e.g 'permission', 'permission.ui'. Or you don't have the full code. There was a recent fix with $inject not correctly working on min builds.

**Comment by stenmuchow** [comment]
Actually its an app I have just started working in that is a bit of a mess - I think they have a factory named permission already
