### ISSUE TITLE
Consider a better name for the module

### ISSUE THREAD

**Issue by dot-louis** [Narzerus/angular-permission#25]
I absolutely love this module. It saves me a lot of time and hassle. I found it browsing SO: http://stackoverflow.com/questions/22537311/angular-ui-router-login-authentication

Just my 2 cents:
Please consider finding a more appropriate name for the module. "permission" is too broad in my opinion.
Maybe something like
  - "router-permission"
  - "auth-route"
  - "redirect-auth"

You get the idea. It's mainly to avoid confusing 2 modules with a close name in the jungle of angular modules.

Thanks again for your work

**Comment by Narzerus** [comment]
"router-permission" sounds good, any other ideas anyone? Once I change the name there's no turning back

- route-access
- route-permissions

Or maybe simply adding a prefix could be enough (we will still need one for the directives)

- nrz-permission
- rte-permission
- ...

Please throw some ideas people, thanks!

**Comment by mabouchalkha** [comment]
I suggest this name
 * ui-router-permission
because its like a addon of ui-router

**Comment by Narzerus** [comment]
What about `route-permissions`

I'd like to keep the "permissions" word in it as it might have helped in organic hits

**Comment by virtual-dev** [comment]
:+1: sold

**Comment by Narzerus** [comment]
I'll be changing the module's name this week then ;)!

**Comment by Narzerus** [comment]
Not sure if I'm actually going to do this. I'll give this more though since it could mean a lot of confusion for everyone, also I wouldn't be able to change the bower package name or the git repo's name

**Comment by virtual-dev** [comment]
yeah I don't know then. You are probably right. It's too confusing.

**Comment by jbender** [comment]
Just my $.02, but I think that this is something that really should happen as it's far more likely to cause confusion in it's current state than the update. Anyone who's using it already can be notified of the change, and since the package is still young I don't think it'll be as much of a problem as you fear.

Secondly, you don't really have to worry about bower at all. It's actually quite easy to make the adjustments that you're talking about, [check out this issue](https://github.com/bower/bower/issues/120) re: removing your existing package and/or updating the location, and [aliasing is currently supported](https://github.com/bower/registry/issues/99) if you wanted to keep the old name up for a while during a transition period and not break people's bower files (blank repo with a README that says to check out the new location?)

**Comment by virtual-dev** [comment]
I did not know about bower aliasing. I guess @jbender has a good point

**Comment by Narzerus** [comment]
@jbender I've never changed a github's repo name so I'm not sure about what the consecuences are.


So basically the changes needed would be:
- Change repo name to `route-permissions`
- Change bower package to `angular-route-permissions`
- Change angular module name to `route-permissions`

Anyone's got any further advice on how to go about this migration?

**Comment by PhiLhoSoft** [comment]
I would keep angular (or ng) in the full name, though. `route-permissions` is too generic (so many JS routers around!), something like `ng-router-permissions` or the full `angular-router-permissions` is better.
Not sure why it got a plural in the process, anyway.

Actually, the more I think of it, the more I believe a name change isn't really necessary...
Most of the time, permissions are tied to page change. Finer permissions (in our app we hide some buttons for some users) are handled at application level, not sure there is a library to manage this simple task. So there is not much ambiguity in the current name.

**Comment by Narzerus** [comment]
Yeah, I'm not sure either. I'm planning on rewriting this module into something MUCH better for angular 2. I think many concepts aren't clear or generic enough to cover the needs of all implementations.

For this reason I will keep the name as it currently is until the complete rewrite is made.

Cheers!

**Comment by PhiLhoSoft** [comment]
"_I think many concepts aren't clear or generic enough to cover the needs of all implementations._"
One important thing, IMHO, would be the capability to distinguish authentication and authorization.
We want different behaviors there.

**Comment by Narzerus** [comment]
Sure, I'll keep that in mind. Expect big changes though, i pretend to
define much more polished concepts for the rewrite.
