### ISSUE TITLE
Blank view on page reload

### ISSUE THREAD

**Issue by ryzhak** [Narzerus/angular-permission#260]
Hello! First of all thank you for this great library.

Problem:
On page reload I can see a blank view when using your library.

Demo: http://ryzhak.com/public/angular_permission_issue/
Source: https://github.com/ryzhak/angular_permission_issue

How to repeat: 
1) click the "admin panel" button
2) after the view is opened reload the page. The view will be blank.

Could you tell me what I am doing wrong?

Thanks in advance

**Comment by axar** [comment]
https://github.com/Narzerus/angular-permission/wiki/Controlling-access-in-views#async-calls-for-permissions-in-initial-states

Check out the doc on async loading permissions.
