### ISSUE TITLE
Properties as roles

### ISSUE THREAD

**Issue by RudmanMario** [Narzerus/angular-permission#273]
Hi,

Is it possible to have permission given to the particular DOM element fetched from the controller? For example: 

```javascript
<div permission permission-only="{{particularRole}}"></div>
```

```javascript
angular.module('example').controller ('testController', function($scope) {
    $scope.particularRole = 'ADMIN'
}
```

**Comment by axar** [comment]
Try without the {{ }}.

**Comment by RudmanMario** [comment]
If I remove double braces then the code in DOM is not connected with `$scope` so that doesn't work for me. I want to be able to change the permission from the controller dynamically.

**Comment by axar** [comment]
Are you using controller as syntax? Either way, permission-only is bound to controller via the '=' syntax; that should evaluate the value against scope. When it gets passed into the controller. That is why you have to pass '' around the permission to ensure it gets evaluated as string. Give it a shot it will work.
