### ISSUE TITLE
Storing permissions in session storage

### ISSUE THREAD

**Issue by saumyapatel** [Narzerus/angular-permission#392]
Currently, when we refresh the page, all the permissions vanishes off. 

Ideal behavior of web-app should allow keeping permissions constant through out the valid session.

**Comment by saumyapatel** [comment]
https://github.com/Narzerus/angular-permission/issues/268 related to this question

**Comment by hsbilgen** [comment]
Both question closed but I couldn't find any answer or the way to do angular-permission to store in localStorage or sessionStorage or Cookies. Can anyone share fiddle for this ? I cannot find the way to do it Issue- #268 and #392 bot marked as closed but no solution i can see please help for this emergency.. @Narzerus @saumyapatel  anyone?
