### ISSUE TITLE
TypeError: k.onUnauthorized(...) is not a function

### ISSUE THREAD

**Issue by kurcob84** [Narzerus/angular-permission#393]
```
TypeError: k.onUnauthorized(...) is not a function

 at j (angular-permission.min.js:11)
    at angular-permission.min.js:11
    at angular.min.js:132
    at m.$eval (angular.min.js:147)
    at m.$digest (angular.min.js:144)
    at m.$apply (angular.min.js:147)
    at l (angular.min.js:99)
    at K (angular.min.js:103)
```

I got this error message in my browser console. Any ideas what goes wrong? I Only inject the angular-permission:

`angular.module('frontendApp', [
        'ui.router',
        'ui.router.state.events',
        'permission',
        'permission.ui',
        'ngCookies',
        'satellizer',
        '720kb.socialshare',
        'pascalprecht.translate',
        'ui.select',
        'ngDialog',
        'LocalStorageModule'
    ]
);`

and used in a template:

```
<li 
        data-ng-repeat="item in menu"
        class="{{item.class}}"
        permission
        permission-only="['USER']"
        permission-on-authorized="PermissionStrategies.showElement"
        permission-on-unauthorized="PermissionStrategies.hideElement"
    >        ...
```

permission-on-unauthorized does not work.

**Comment by joaoGabrielSalgado** [comment]
+1

**Comment by xavhan** [comment]
You should get the `showElement` function in the controller and attach it to the scope and then use it in the template

in controller: 
```
this.showElement = PermissionStrategies.showElement;
this.hideElement = PermissionStrategies. hideElement;
```
in template:
```
permission-on-authorized="showElement"
permission-on-unauthorized="hideElement"
```

**Comment by joaoGabrielSalgado** [comment]
Works, thanks

**Comment by hughesadam87** [comment]
I had this error and was unable to get it working with `$ctrl` using angular 1.X.  Ultimately this is the exact syntax we used give angular-permissions 6.0.0. - in case helpful to anyone

HTML

        <button permission
                permission-only="['CAN_FREEFORM_ADDRESS']"
                permission-on-authorized="vm.enableElement"
                permission-on-unauthorized="vm.disableElement">test</button>


JS

        angular.module('cityStateZipComposite', []).component('cityStateZipComposite', {
            templateUrl: 'app/components/common/city-state-zip/city-state-zip-composite.template.html',
            controllerAs: 'vm',
            },
            controller: ['PermissionStrategies',
                function (PermissionStrategies) {
                    const vm = this;
                    vm.enableElement = PermissionStrategies.enableElement;
                    vm.disableElement = PermissionStrategies.disableElement;
                }
            ]

This `vm` variable is a convention we use in our apps (before my time) and not really sure if its standard or not.
