### ISSUE TITLE
Unhandled rejection for resolvePropertyValidity with Angular 1.6 

### ISSUE THREAD

**Issue by jiki974** [Narzerus/angular-permission#402]
In angular-permission-ui.js the function resolveStatePermissionMap call map.resolvePropertyValidity(statePrivileges), a success function exist  : 

**function (resolvedPermissions) {
            if (angular.isArray(resolvedPermissions)) {
              return resolvedPermissions[0];
            }
            return resolvedPermissions;
          }**

But no rejection function and with angular 1.6, I got an _"Possibly unhandled rejection:undefined"._ error.

**Comment by bampakoa** [comment]
@jiki974 After some tests, I think that the actual method is [this](https://github.com/Narzerus/angular-permission/blob/e3823e98394b47ef26ad1e3d2c21458ac8f28533/src/permission-ui/permission-ui.js#L135) one
