### ISSUE TITLE
Permission in state do nothing

### ISSUE THREAD

**Issue by darkterra** [Narzerus/angular-permission#410]
Hi,

I do not understand why permissions do not work, but my code is as explained in the wiki.
Anyone with an idea of ​​the mistake I made?

Im using :
  - Angular 1.5.11
  - Angular-ui-router 1.0.0-beta.3
  - Angular-permission 5.2.3
  - Angular-permission-ui 5.2.3
here's my code:

This is Working (in view) :
```<div permission permission-only="['ADMIN_ARTICLE]" >
  <span>Congrats! You are logged in.</span>
</div>
```

This is not Working (in config) :
```
.state('admin.articles', {
  url         : '/adminArticles',
  templateUrl : '../Partial/Admin/adminArticles.html',
  data        : {
     permissions: {
      only: ['ADMIN_ARTICLE'],
      redirectTo: 'home'
    }
  }
})
```

Thanks in Advance!

**Comment by olegdemkovych** [comment]
try downgrade ui-router to 0.4.2
