### ISSUE TITLE
Any example of defining Permission before permission.ui load

### ISSUE THREAD

**Issue by mike623** [Narzerus/angular-permission#439]
So, I am using permission with `ui-router`. But `permission.ui` is loaded and started to check permission before I define the role (because it is async). It happens only on bootstrap first load(e.g refresh). Any example to setup permission before `permission.ui` load?

**Comment by jkeczan** [comment]
I do that in my current project. What you need to do is wait on the on the permission before you activate the router. The following code is what I use:


my .run function in app.js
`
 loginService.checkSession().then(function (session) {
return new Promise(function(resolve, reject) {
 PermPermissionStore.definePermission('isAuthenticated', function () {
      return Promise.resolve(session);
    });
})

  }).then(function (session) {
    PermPermissionStore.definePermission(session.securityGroup, function () {
      return Promise.resolve(true);
    });

  }).then(function () {
    $urlRouter.sync();
    $urlRouter.listen();
  }).catch(function (err) {
    $state.go('login');
  });

`
