### ISSUE TITLE
How to add url parameters for redirectTo ?

### ISSUE THREAD

**Issue by JosephBuchma** [Narzerus/angular-permission#45]
Hi.
I'm looking for something like this:
```coffeescript
$stateProvider 
	.state 'dashboard',
		url: '/dashboard'
		views:
			"sidebar": templateUrl: 'views/dashboard/sidebar.html'
			"content": templateUrl: 'views/dashboard/content.html'
		data:
			permissions:
				only: ['authorized']
				redirectTo: 'loading'
				redirectToParams: {next: 'dashboard'}
```

**Comment by Narzerus** [comment]
I'm not sure there's currently a way to do this, though I understand the use. If you feel like it please submit a PR and I'll check your solution. I'm currently very busy and have been ahving a hard time maintaining the module

**Comment by Narzerus** [comment]
This is the same as #26 please help voting for the following issue at the ui-router repo: [Issue](https://github.com/angular-ui/ui-router/issues/1620)

**Comment by zamrokk** [comment]
:+1:
