### ISSUE TITLE
Redirect Back to the URL he came from

### ISSUE THREAD

**Issue by artmees** [Narzerus/angular-permission#46]
I'm using this module with in a project... I'm facing the issue that I need to redirect back to where the user intended after he sign in... but I can't figure that out

here is a snippet of the code to grasp what I'm trying to achieve
```coffee
    .state 'user.confirm',
      url: '/auth/confirmations/:confirmationToken'
      templateUrl: 'app/auth/confirm_email.html'
      controller: 'ConfirmationCtrl'
      controllerAs: 'confirm'
      data:
        permissions:
          only: ['user']
          redirectTo: 'user.login' 
```
this is basically used with confirming user emails... If the user is not logged in ... he is redirected to login
but after he login... he is redirected to the home page not back to the url `/auth/confirmations/:confirmationToken`

**Comment by Narzerus** [comment]
This is the same as #46 please help voting for the following issue at the ui-router repo: [Issue](https://github.com/angular-ui/ui-router/issues/1620)

**Comment by karser** [comment]
+1
