### ISSUE TITLE
Integrating permissions/roles with UI elements

### ISSUE THREAD

**Issue by sjl2024** [Narzerus/angular-permission#53]
Hey! This seems like an excellent module. I was a bit curious as to the best way to say, show or hide navigation items (or anything else in the DOM) based on roles. Does this module have any impact on that, or can such information be determined based on states alone (from ui.router)?

Thanks a ton.

**Comment by Narzerus** [comment]
We are actually discussing exactly this at #40 feel free to join the conversation!
