### ISSUE TITLE
User is not available right after login

### ISSUE THREAD

**Issue by timotheemoulin** [Narzerus/angular-permission#55]
Hi,
When using angular-permission on the page displayed right after the login process, the user (Authentication.user) is not defined which causes the permission check to fail.

Is there any way to achieve the following?

authentication client controller
```js
$scope.homeUrl = function () {
            $scope.signup = function () {
            $http.post('/auth/signup', $scope.credentials).success(function (response) {
                // If successful we assign the response to the global user model
                $scope.authentication.user = response;

                // And redirect to the index page
                $location.path('/myProtectedUrl');
            }).error(function (response) {
                $scope.error = response.message;
            });
        };
```

somewhere else in another module
```js
angular.module('dashboard').run(['$rootScope', 'Permission', 'Authentication',
    // Definition of the roles used by the app router
    function ($rootScope, Permission, Authentication) {
        var user = Authentication.user;
        // HERE MY USER IS ALWAYS EMPTY
        Permission.('anonymous', function ($stateParams) {
                return (user === null);
            });
    }]);
```

BTW, I'm using the mean stack.

Thanks for your help!
tim

**Comment by timotheemoulin** [comment]
Hi,
It seems that I have to retrieve the Authentication provider in my Permission Role Callback to get its value, else I always receive an empty User object as the 
```js
var user = Authentication.user
```
on the 4th line seems to be called only once.

Here is my final code if anyone is interested
```js
.run(['Permission', 'Authentication',
    // Definition of the roles used by the app router
    function (Permission, Authentication) {
        Permission
            .defineRole('anonymous', function ($stateParams) {
                return (Authentication.user === null);
            });
    }]);
```

**Comment by Narzerus** [comment]
Yup, this is because you were assigning `null` to your `user` var.

The other solution is to make user an object in the first place and update the object. But the solution to your own problem is the right way to go.

Closing this because it's an application issue and not Permission's.

Cheers
