### ISSUE TITLE
abstract states not supported?

### ISSUE THREAD

**Issue by jelkevdh** [Narzerus/angular-permission#58]
Hi,

I'm trying this module and it looks pretty nice :)
A bit further in, I noticed that if I set the permission on an abstract parent state, it is not checked.
Is this behavior not supported, or am I doing it wrong?

Thanks,
Jelke

**Comment by Narzerus** [comment]
It should be checked, are you setting your permissions inside the data
property?

**Comment by jelkevdh** [comment]
Wow, thanks for the fast reply!

Yes I am. I think I'm doing it right.
Some code snipets:

Permission.defineRole('anonymous', function() {
   return true;
});
Permission.defineRole('admin', function() {
   return false;
});

myApp
    .config(['$stateProvider', '$urlRouterProvider', function ($stateProvider, $urlRouterProvider) {
            // State Configurations
            $stateProvider
                // Login Page
                .state("login", {
                    data: {
                        permissions: {
                            only: ['anonymous'],
                            redirectTo: 'auth.home'
                        }
                    },
                    page_title: 'Login Page',
                    url: "/login",
                    templateUrl: 'views/login.html',
                    controller: 'loginCtrl'
                })
                // Authenticated
                .state("auth", {
                    abstract: true,
                    url: "",
                    date: {
                        permissions: {
                            only: ['admin'],
                            redirectTo: 'login'
                        }
                    },
                    templateUrl: 'views/authenticated.html'
                })
                // Dashboard
                .state("auth.home", {
                    // this state page title
                    page_title: 'Dashboard',
                    // this state url
                    url: "/",
                    templateUrl: 'views/dashboard.html',
                    data: {
                        ncyBreadcrumbLabel: 'Home'
                    },
                    controller: 'dashboardCtrl'
                })

**Comment by Narzerus** [comment]
Hmm I see, I'll look into this I can't remember if this is expected
behavior and I'm not near my computer right now.

Cheers!

**Comment by jelkevdh** [comment]
Ok thanks

**Comment by jelkevdh** [comment]
Oh it's a duplicate of issue #13 :|

**Comment by Narzerus** [comment]
Oooooh, yes, sorry I was not very focused at the moment I read this. we're waiting for ui-team to provide the route options on events.

Closing since its a dupe.
