### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by jgoux** [Narzerus/angular-permission#60]
Hello,
could you publish your library on NPM, as all angular core libraries are published as well so we don't have to support both bower and NPM ? :)

**Comment by Narzerus** [comment]
Thanks for your contribution!

Sorry for my ignorance but, may I ask why we need Permission set as a `peerDependency`?

**Comment by jgoux** [comment]
Permission isn't in the peer dependencies, ui-router is. :)
Here is a good link to understand peer dependencies : http://blog.nodejs.org/2013/02/07/peer-dependencies/

**Comment by Narzerus** [comment]
Ohh, that makes sense, sorry I was a little distracted when I read this.

Ok sure man, lets merge this, I'll publish to NPM right away

**Comment by Narzerus** [comment]
Closing this issue because it was addressed at #61
