### ISSUE TITLE
Adding alert

### ISSUE THREAD

**Issue by davidbonachera** [Narzerus/angular-permission#63]
Hello,

just trying to help a bit and i'm quite new in this world. But should it be a good idea to return alert message when an access is denied by permissions ?

By the way it's a very nice module ;) thanks you for this.

**Comment by Narzerus** [comment]
Not really, as a module we want to stay as agnostic as possible to the app being developed. Adding an alert message is something not everyone wants in their app, though it is something that should be possible.

You can do this if you need to by using the `$stateChangePermissionDenied` event.
