### ISSUE TITLE
Demo integrations with FreeIPA & AD

### ISSUE THREAD

**Issue by briantopping** [Narzerus/angular-permission#67]
As a source of permission data, consider https://www.freeipa.org. It is a very robust and mature open source project that provides a users/roles/permissions control plane similar to what is provided by Microsoft AD, and in many cases exceeding it. I think it would be very helpful for users to see a demo connecting these important technologies to angular-permission.

In highly secure environments (i.e. anything that doesn't want to be hacked), it's important that the control plane is built on third party software, not ad-hoc by the members of the product development team. This allows someone with the role of Chief Security Officer to have a silo that is completely separated from the data silo that customer data is stored in. In this manner, an errant CSO cannot get access to customer data and an errant programmer cannot get access to usernames and passwords. This forms what is known as a "two man rule", requiring more than one person in conspiracy to retrieve actionable system data.

Exceptional deployments go so far as to make sure that all identifying information about users is stored in the security database (LDAP). A breach of the application data yields a completely anonymized database, even if the data is not encrypted. A breach of the security database provides no data about customers, only that they exist. 

Would love to hear the thoughts of others on this!

**Comment by Narzerus** [comment]
I'm not sure this should be part of permission, remember this module **does not** improve security in the application, it simply controls front-end route access, something which can be modified via any browser console.

l

**Comment by briantopping** [comment]
Would you agree that front-end permissions are for the convenience of users and not for actual domain security? Anyone with CURL and the API can go around the front end. 

Rather, front end permissions help guide "collaborative users" (i.e. those trying to benefit from the features of an application and it's community rather than hacking the app) with visual guidance of their app entitlements. 

Apps that can't change their UI to guide the user by disabling or eliminating that are unavailable based on the user's authorization context and frustrating and cumbersome to use. (It's easy to imagine an app with administrator links all over it, and none of them work for most users.)

Could you help me understand where this vision is divergent with yours?

**Comment by Narzerus** [comment]
@briantopping I agree that front-end permissions are not a security implementation. It is always necessary to provide the security functionality through the back-end.

The idea behind Permission is to help developers structure the way they manage front-end access to certain routes, and how those accesses are redirected.
