### ISSUE TITLE
Use permission other then ui-router

### ISSUE THREAD

**Issue by minipai** [Narzerus/angular-permission#75]
Is there a way to use existing role set on angular-permission?
I want to hide some UI base on role.

**Comment by chaaya** [comment]
Not at the moment. Look at issue #40. I have posted some ideas

**Comment by minipai** [comment]
Thanks for reply :)

**Comment by chaaya** [comment]
You could call authorize from your controller, I think the author posted an example on that in the thread. But there isnt any directive yet

**Comment by Narzerus** [comment]
Thanks for answering this, closing issue, cheers
