### ISSUE TITLE
[feature] Permission.defineManyRoles + $q.promise

### ISSUE THREAD

**Issue by danfergo** [Narzerus/angular-permission#80]
A way of defining all the roles at once. Equals to the current Permission.defineRole but we sould be able to pass an array to resolve and reject of which roles were accepted and rejected.

**Comment by Narzerus** [comment]
Can you explain more in details what this feature request is about? I dind't really understand

**Comment by danfergo** [comment]
For example, i have an API service $.get which at the handler returns all the session data needed to know what is the current role. So it would be usefull to do something like this:

.defineMultipleRoles([...], function (stateParams) {
                var defer = $q.defer();
                accountService.pullSession().then(function (data) {
                    ...
                   defer.resolve(['admin', 'user', 'manager']);
                    ...
                   defer.resolve(['admin']);
                   ...
                    defer.reject(['anonymous']);
                }, function () {
                    defer.resolve(['anonymous']);
                });
                return defer.promise;
            })

**Comment by Narzerus** [comment]
This doesn't really makes sense as `defineMultipleRoles` runs once **per role defined**

This means you should do something like this:

```javascript
.defineMultipleRoles(['admin', 'user', 'manager', 'anonymous'], function (stateParams, roleName) {
  // ... Do some checking with roleName
  // for example:
  if (roleName === 'anonymous') {
    return !User.hasSession(); // Will resolve as anonymous if use doesn't have a session
  }
  if (roleName === 'manager') {
    return User.isManager();
  }
  // ... and so on ... //
});
```

**Comment by danfergo** [comment]
when i said defineMultipleRoles i meant some "the new function". 
but in that case defineMultipleRoles does not consider asynchronous such as $.get does.

**Comment by Narzerus** [comment]
I'm pretty sure `defineMultipleRoles` uses `defineRole` in the background, that being the case, you can return a promise.

The condition is: If the promise resolves, the session has the role, if the promise rejects, then the user doesn't have the role.

**Comment by danfergo** [comment]
Oh ok. didn't noticed that. 
but in that case the $.get request wouldn't be called 'n' times? (being n the number of roles)

**Comment by Narzerus** [comment]
Yeah, therefore you should cache that response in a service or via standard caching itself.

I'd suggest having some sort of User/Session service and inject it into the module where you are defining the roles.

Then you could have a method called `getSessionData` or something, and have it return a promise (which is the same for every request, this means it will only request the server once, and the next times return its response on its resolve callback).

Hope this helps, closing this issue
