### ISSUE TITLE
Possible error in rejection

### ISSUE THREAD

**Issue by PhiLhoSoft** [Narzerus/angular-permission#82]
In current (0.3.1) code, at line 58, I see the same test than in the resolve part:
`if (!$rootScope.$broadcast('$stateChangeStart', toState, toParams, fromState, fromParams).defaultPrevented)`

This can lead to reject the state change on the basis we want to go to toState, while we want the check to be done on the redirectTo state.

[EDIT] I am no longer sure of the validity of my issue...
Sorry for the noise, this probably should be closed.

**Comment by Narzerus** [comment]
No worries!
