### ISSUE TITLE
how can I stop the http request in the promise if the network failed?

### ISSUE THREAD

**Issue by lijax** [Narzerus/angular-permission#87]
When I define a role using a promise with HTTP request, if there is a network problem, the promise will reject, but the permission will keep making requests. How can I stop this?

```
Permission
        .defineRole('anonymous', function(stateParams) {
            if (!User.getLocalIdentity()) {
                return true;
            }
            return false;
        })
        .defineRole('user', function(stateParams) {
            if (!User.getLocalIdentity()) {
                return false;
            } else {
                return User.isLogin();
            }
        });
```

**Comment by Narzerus** [comment]
There's two ways you can go about this:

1: Save the login state in `User` so that once the request has been done subsequent requests return the resolved promise

2: Use some form of caching to avoid the request actually going through.

**Comment by lijax** [comment]
Hi, @Narzerus 
Thanks for your help!
The problem is, if the http request failed, the rejected promise seems cannot set the role 'user' to false. It keep make the request for a resolved state.
